### ISSUE TITLE
1.20.4 fabric support

### ISSUE THREAD

**Issue by Felonale** [cakeGit/Watering-Overlay-Mod#2]
Hi, friend! A very unique mod for lovers of decorative fields. If possible, please provide support for 1.20.4 on [Better Farming Right Click](https://www.curseforge.com/minecraft/mc-mods/better-farming-right-click). Good luck with your future projects! ;)

**Comment by cakeGit** [comment]
Thanks for the comment 😊, i don't believe there is any change between 1.20.6 and 4 so I'll get you a port soon, is this for both mods or just better farming right click?

**Comment by Felonale** [comment]
Yeah, for both. Im just mentioning that I really need both mods :)

**Comment by cakeGit** [comment]
Alright, I'll get to it later today, out of interest could I see a fellow farming lovers fields?

**Comment by Felonale** [comment]
Oh, sure! This is just a great start, but Im looking forward to do the greatest field on the server!
![2024-07-04_20 58 56](https://github.com/cakeGit/Watering-Overlay-Mod/assets/104564112/b10c4db1-4131-4fb6-887a-491489157c8a)

**Comment by cakeGit** [comment]
Beautiful, love the paths too, is this port for fabric? (ive got seperate versions of the mod so ill have to port them seperatley)

**Comment by Felonale** [comment]
Yeah, sorry. I was busy. Fabric as I said in topic. 1.20.4 fabric for both mods!

**Comment by cakeGit** [comment]
just seen that mb, ill get to it now

**Comment by cakeGit** [comment]
Somethings up with the better farming right click but heres a port for watering overlay
its very late today so ill probably get the other one tomorrow
[Heres the jar for the watering overlay](https://github.com/cakeGit/Watering-Overlay-Mod/blob/main/watering-overlay-fabric-1.20.4-1.0.0.jar)

**Comment by cakeGit** [comment]
Ports done ill upload them now,

**Comment by cakeGit** [comment]
Ports uploaded, please tell me if you have any issues!
